services:
  api:
    image: amazoncorretto:21  
    container_name: api-spring  
    command: sh -c "mkdir -p /usr/share/api && java -jar /usr/share/api/app_refuge.jar"  
    volumes: 
      - /usr/share/api:/usr/share/api  
    ports:
      - "8080:8080"  



